services:
  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1027 #CHANGE_TO_YOUR_UID
      - PGID=65536 #CHANGE_TO_YOUR_GID
      - TZ=Europe/Amsterdam #CHANGE_TO_YOUR_TZ
      - UMASK=022
    volumes:
      - /volume1/docker/sonarr:/config
      - /volume1/data:/data
    ports:
      - 8989:8989/tcp
    network_mode: synobridge
    security_opt:
      - no-new-privileges:true
    restart: always

  lidarr:
    image: linuxserver/lidarr:latest
    container_name: lidarrgit 
    environment:
      - PUID=1027 #CHANGE_TO_YOUR_UID
      - PGID=65536 #CHANGE_TO_YOUR_GID
      - TZ=Europe/Amsterdam #CHANGE_TO_YOUR_TZ
      - UMASK=022
    volumes:
      - /volume1/docker/lidarr:/config
      - /volume1/data:/data
    ports:
      - 8686:8686/tcp
    network_mode: synobridge
    security_opt:
      - no-new-privileges:true
    restart: always

  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1027 #CHANGE_TO_YOUR_UID
      - PGID=65536 #CHANGE_TO_YOUR_GID
      - TZ=Europe/Amsterdam #CHANGE_TO_YOUR_TZ
      - UMASK=022
    volumes:
      - /volume1/docker/radarr:/config
      - /volume1/data:/data
    ports:
      - 7878:7878/tcp
    network_mode: synobridge
    security_opt:
      - no-new-privileges:true
    restart: always

  readarr:
    image: linuxserver/readarr:develop
    container_name: readarr
    environment:
      - PUID=1027 #CHANGE_TO_YOUR_UID
      - PGID=65536 #CHANGE_TO_YOUR_GID
      - TZ=Europe/Amsterdam #CHANGE_TO_YOUR_TZ
      - UMASK=022
    volumes:
      - /volume1/docker/readarr:/config
      - /volume1/data/:/data
    ports:
      - 8787:8787/tcp
    network_mode: synobridge
    security_opt:
      - no-new-privileges:true
    restart: always

  bazarr:
    image: linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=1027 #CHANGE_TO_YOUR_UID
      - PGID=65536 #CHANGE_TO_YOUR_GID
      - TZ=Europe/Amsterdam #CHANGE_TO_YOUR_TZ
      - UMASK=022
    volumes:
      - /volume1/docker/bazarr:/config
      - /volume1/data/:/data
    ports:
      - 6767:6767/tcp
    network_mode: synobridge
    security_opt:
      - no-new-privileges:true
    restart: always

  sabnzbd:
    image: linuxserver/sabnzbd:latest
    container_name: sabnzbd
    environment:
      - PUID=1027 #CHANGE_TO_YOUR_UID
      - PGID=65536 #CHANGE_TO_YOUR_GID
      - TZ=Europe/Amsterdam #CHANGE_TO_YOUR_TZ
      - UMASK=022
    volumes:
      - /volume1/docker/sabnzbd:/config
      - /volume1/data/usenet:/data/usenet
    ports:
      - 8080:8080/tcp
    network_mode: synobridge
    security_opt:
      - no-new-privileges:true
    restart: always

  plex:
    image: linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1027 #CHANGE_TO_YOUR_UID
      - PGID=65536 #CHANGE_TO_YOUR_GID
      - TZ=Europe/Amsterdam #CHANGE_TO_YOUR_TZ
      - UMASK=022
      - VERSION=docker
      - PLEX_CLAIM= #Your Plex Claim Code
    volumes:
      - /volume1/docker/plex:/config
      - /volume1/data/media:/data/media
    devices:
      - /dev/dri:/dev/dri
    security_opt:
      - no-new-privileges:true
    restart: always

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    user: 1027:65536 #YOUR_UID_AND_GID
    environment:
      - TZ=Europe/Amsterdam #CHANGE_TO_YOUR_TZ
    volumes:
      - /volume1/docker/jellyseerr:/app/config
    ports:
      - 5055:5055/tcp
    network_mode: synobridge
    dns: #DNS Servers to help with speed issues some have
      - 9.9.9.9
      - 1.1.1.1
    security_opt:
      - no-new-privileges:true
    restart: always

   tautulli:
    image: linuxserver/tautulli:latest
    container_name: tautulli
    environment:
      - PUID=1027 #CHANGE_TO_YOUR_UID
      - PGID=65536 #CHANGE_TO_YOUR_GID
      - TZ=Europe/Amsterdam #CHANGE_TO_YOUR_TZ
      - UMASK=022
    volumes:
      - /volume1/docker/tautulli:/config
    ports:
      - 8181:8181/tcp
    network_mode: synobridge
    security_opt:
      - no-new-privileges:true
    restart: always

  tunnel:
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run
    env_file: tunnel.env
    restart: always
    container_name: tunnel
    depends_on:
      - jellyseerr
