services:
  logseq:
    image: logseq/logseq:latest
    container_name: logseq
    ports:
      - 5173:80
    volumes:
      - /volume2/docker/logseq:/data
    environment:
      - LOGSEQ_USER=obakker
      - LOGSEQ_PASSWORD=blikblik
    restart: unless-stopped